
import {Playfair_Display as FontSans} from "next/font/google"
import "../../styles/globals.css";
import { cn } from "../lib/utils"
import Navbar from "@/components/Navbar";
import React from "react";
import Home from "./page";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Film Trackr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
        >
      <Navbar/>
      <Home/>
      </body>
    </html>
  );
}
